### ISSUE TITLE
$u = User::remember(1)->first()

### ISSUE THREAD

**Issue by r17x** [mongodb-php/laravel-mongodb#1101]
![image](https://cloud.githubusercontent.com/assets/16365952/22544869/8eaa3d5a-e971-11e6-9186-8314f6c4db9d.png)
what this ? on my model can't user remember "query cache"

**Comment by Wu4m4n** [comment]
I have the same issue!

**Comment by GromNaN** [comment]
Closing as duplicate for #1040
