### ISSUE TITLE
Trying to use raw query in select

### ISSUE THREAD

**Issue by jbxonline** [mongodb-php/laravel-mongodb#1123]
I've been going round in circles a bit here - hoping someone can help or tell me what I'm doing wrong!

This query works fine:
```
$query = \DB::connection('mongodb')
        ->collection('statistics')
        ->whereIn('vehicle.branch_id', $branchIds)
        ->select(['event', 'created_at', 'vehicle.vin'])
        ->get();
```

However, I want to use raw, in order to return a column with a different name, and also perform aggregations:
```
$query = \DB::connection('mongodb')
        ->collection('statistics')
        ->whereIn('vehicle.branch_id', $branchIds)
        ->select(['event', 'created_at', \DB::raw('vehicle.vin as vin'), \DB::raw('COUNT(*) as count')])
        ->get();
```

This always gives me an Illegal Offset type in Builder.php line 353, as it is expecting an array of column names, but it gets instances of Expression.

I've tried building this query a few different ways, but can't get past this issue.
Any ideas?

TIA, Jon

**Comment by BigKuCha** [comment]
same issue,want help~~ 🆘

**Comment by trungdiep92** [comment]
Why don't you fix this? It has existed for a long time.

**Comment by narenthiran** [comment]
I am also facing this issue. Still no update on this?

**Comment by GromNaN** [comment]
Raw SQL cannot be used with MongoDB. This is expected. Outside of Eloquent models, you can get the full power of the [MongoDB PHP library](https://github.com/mongodb/mongo-php-library) like this:

```
DB::connection('mongodb')->getCollection('statistics')
  ->aggregate(/* your aggregation pipeline */);
```

**Comment by GromNaN** [comment]
Related to #1172
