### ISSUE TITLE
auth()->guard('user')->user() not working jenssegers mongodb

### ISSUE THREAD

**Issue by manektechmehul** [mongodb-php/laravel-mongodb#1212]
Hi, I am using laravel 5.4 and jenssegers mongodb.
I am using "use Jenssegers\Mongodb\Auth\User as Authenticatable;" for default auth functionality of laravel 5.4 Auth.
But i can't login because "auth()->guard('user')->user()" not working.
Help me please.

**Comment by banqhsia** [comment]
How does it not working? 
Though you've `use` that class, have you extend it correctly? 

    class User extends Authenticatable { }
