### ISSUE TITLE
reversed whereBetween

### ISSUE THREAD

**Issue by thiagovictorino** [mongodb-php/laravel-mongodb#1301]
I tried to use the function whereBetween() but I realized that that start and end is reversed.

The first argument is $lte and the second is $gte

**File: src/Jessengers/MongoDB/Query/Builder.php
Line: 1038**
```
protected function compileWhereBetween(array $where)
    {
        extract($where);

        if ($not) {
            return [
                '$or' => [
                    [
                        $column => [
                            **'$lte' => $values[0],**
                        ],
                    ],
                    [
                        $column => [
                            **'$gte' => $values[1],**
                        ],
                    ],
                ],
            ];
        } else {
            return [
                $column => [
                    '$gte' => $values[0],
                    '$lte' => $values[1],
                ],
            ];
        }
    }
```

See that in the else condition is correct.

**Comment by lindelius** [comment]
The order in which you put `$lte` and `$gte` shouldn't make any difference.

**Comment by lindelius** [comment]
The method is correct as it is. The code within the `if` part is for when we do **not** want to get results where the values are within the given range.

For example:

```
...->whereBetween('field', [1, 100])->get();
```
will output results where the `field` field is either 1, 100, or somewhere in between (the `else` part).

```
...->whereBetween('field', [1, 100], 'and', true)->get();
```
will output results where the `field` field is neither 1, 100, nor somwhere in between (the `if` part).

**Comment by GromNaN** [comment]
This is correct, as proved by this test: https://github.com/mongodb-php/laravel-mongodb/blob/e652b0c5f1fdf0ebca30118ee566ed0195cf2c28/tests/QueryTest.php#L169-L171
