### ISSUE TITLE
get by random order

### ISSUE THREAD

**Issue by saeedvz** [mongodb-php/laravel-mongodb#1493]
Laravel has inRandomOrder() method on collections.

How to get documents by random order here?

Is it possible?

**Comment by xxCryptoxx** [comment]
`$randomUser = User::all()->inRandomOrder()->first();`
this might work if not
`$randomUser = DB::table('users') ->inRandomOrder() ->first();`

**Comment by thureos** [comment]
Thanks @xxCryptoxx , but non of this worked.

I got this with both eloquent or query builder.

` [MongoDB\Driver\Exception\ServerException] bad sort specification`

**Comment by leelijin** [comment]
same question

**Comment by Didstriker** [comment]
Got the same problem and just found out that MongoDB has no built-in way to return random documents.

There is something similar though, from version 3.2 (https://docs.mongodb.com/manual/reference/operator/aggregation/sample/) but as the docs say, it might return more than once the same record on a request. 

Used it on my code like; 
`$result = myModel::raw(function($collection){
return $collection->aggregate([
                ['$sample' => ['size' => 3]]
            ]);
})`

**Comment by Jaffer2x** [comment]
> 
> 
> Got the same problem and just found out that MongoDB has no built-in way to return random documents.
> 
> There is something similar though, from version 3.2 (https://docs.mongodb.com/manual/reference/operator/aggregation/sample/) but as the docs say, it might return more than once the same record on a request.
> 
> Used it on my code like;
> `$result = myModel::raw(function($collection){ return $collection->aggregate([ ['$sample' => ['size' => 3]] ]); })`

Thank u!! worked like a charm. I just need to figure out how to add a condition and i done.

**Comment by farad4y** [comment]
@Didstriker Thank you 👶🏼

**Comment by rajatmasih-web4realty** [comment]
You should try this.
`$total_records = $your_model->count();`
`if ($total_records > 0){`
`	$randIndex = rand(0, $total_records-1);`
`	$obj = $your_model->skip($randIndex)->get();`
`}`

**Comment by GromNaN** [comment]
Thanks for the provided solution https://github.com/mongodb-php/laravel-mongodb/issues/1493#issuecomment-452664988

**Comment by Giacomo92** [comment]
@GromNaN Do you think a new method sample() or inRandomOrder() can be added?

See #1967

**Comment by GromNaN** [comment]
We are going to work on an aggregation builder in the coming month, which will provide a lot more features with an unified interface. I don't think an opininiated method is necessary at this point.

**Comment by Giacomo92** [comment]
Ok thanks! Maybe an example can be added on docs.
