### ISSUE TITLE
Demo for laravel demo project using this library

### ISSUE THREAD

**Issue by Smolevich** [mongodb-php/laravel-mongodb#1927]
I created this repo https://github.com/Smolevich/demo-mongo-application as demo laravel project using this library

**What is the main purpose?**
Often users of this library create issues where they about not working code. For this case you can clone this repo, run docker containers (php, nginx, mongo as required) and test code on this configuration. Some questions are can be resolved on this step. Or you can find bug and for demo you can prepare PR with minimal code for reproducing him 

Any comments about improvement are welcome

**Comment by GromNaN** [comment]
Thanks for the initiative. The demo app is now outdated. To be really useful it needs to have a good test coverage.
