### ISSUE TITLE
laravel mongodb used countDocuments() or estimatedDocumentCount() ?

### ISSUE THREAD

**Issue by tristan5293** [mongodb-php/laravel-mongodb#2548]
How can I use countDocuments() and estimatedDocumentCount()?

NOTE:
MongoDB drivers compatible with the 4.0 features deprecate their respective cursor and collection count() APIs in favor of new APIs for countDocuments() and estimatedDocumentCount(). For the specific API names for a given driver, see the driver documentation.

**Comment by GromNaN** [comment]
Fixed by 4514964145c70c37e6221be8823f8f73a201c259
